# Generated by Django 6.0.2 on 2026-06-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('streak', 'Streak'), ('learning', 'Learning'), ('cracking', 'Cracking')], max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('requirement', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['category', 'requirement'],
            },
        ),
    ]
