# Generated by Django 6.0.2 on 2026-06-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_level',
            field=models.CharField(blank=True, max_length=50, verbose_name='experience level'),
        ),
        migrations.AddField(
            model_name='user',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='github url'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='linkedin url'),
        ),
        migrations.AddField(
            model_name='user',
            name='target_role',
            field=models.CharField(blank=True, max_length=100, verbose_name='target role'),
        ),
    ]
