# Generated by Django 6.0.2 on 2026-06-19 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Machine-readable code, e.g. INTERVIEW_STARTED.', max_length=50, unique=True, verbose_name='status code')),
                ('name', models.CharField(help_text='Human-readable label shown in the UI.', max_length=100, verbose_name='display name')),
                ('category', models.CharField(choices=[('INTERVIEW', 'Interview'), ('USER', 'User')], db_index=True, help_text='Logical grouping for this status.', max_length=30, verbose_name='category')),
                ('order', models.PositiveIntegerField(default=0, help_text='Determines display / workflow ordering.', verbose_name='display order')),
                ('is_terminal', models.BooleanField(default=False, help_text='If True, no further transitions are allowed from this status.', verbose_name='terminal state')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete flag — inactive statuses are hidden from new workflows.', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'status',
                'verbose_name_plural': 'statuses',
                'db_table': 'interviews_status',
                'ordering': ['category', 'order'],
                'indexes': [models.Index(fields=['category', 'order'], name='idx_status_cat_order')],
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DSA', 'Data Structures & Algorithms'), ('SYSTEM_DESIGN', 'System Design')], max_length=30, verbose_name='interview type')),
                ('question', models.TextField(verbose_name='question')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interview_sessions', to='interviews.status', verbose_name='status')),
            ],
            options={
                'verbose_name': 'interview session',
                'verbose_name_plural': 'interview sessions',
                'db_table': 'interviews_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive transitions are not considered by the workflow engine.', verbose_name='active')),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions_from', to='interviews.status', verbose_name='from status')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions_to', to='interviews.status', verbose_name='to status')),
            ],
            options={
                'verbose_name': 'status transition',
                'verbose_name_plural': 'status transitions',
                'db_table': 'interviews_status_transition',
                'ordering': ['from_status', 'to_status'],
            },
        ),
        migrations.CreateModel(
            name='AIEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='Overall score assigned by the AI evaluator (0-100).', verbose_name='score')),
                ('strengths', models.JSONField(default=list, help_text='List of identified strengths.', verbose_name='strengths')),
                ('weaknesses', models.JSONField(default=list, help_text='List of identified weaknesses.', verbose_name='weaknesses')),
                ('improvements', models.JSONField(default=list, help_text='Actionable improvement suggestions.', verbose_name='improvements')),
                ('raw_response', models.JSONField(default=dict, help_text='Full unprocessed response from the AI provider for auditing.', verbose_name='raw AI response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='interviews.interviewsession', verbose_name='interview session')),
            ],
            options={
                'verbose_name': 'AI evaluation',
                'verbose_name_plural': 'AI evaluations',
                'db_table': 'interviews_ai_evaluation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['interview'], name='idx_eval_interview')],
            },
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['user'], name='idx_session_user'),
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['status'], name='idx_session_status'),
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['-created_at'], name='idx_session_created'),
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['user', 'status'], name='idx_session_user_status'),
        ),
        migrations.AddConstraint(
            model_name='statustransition',
            constraint=models.UniqueConstraint(fields=('from_status', 'to_status'), name='uq_status_transition'),
        ),
    ]
