# Generated by Django 6.0.2 on 2026-06-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='chat_history',
            field=models.JSONField(blank=True, default=list, help_text='Stores the conversation history with the AI agent.', verbose_name='chat history'),
        ),
    ]
