# Generated by Django 6.0.2 on 2026-06-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewsession_chat_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='type',
            field=models.CharField(choices=[('DSA', 'Data Structures & Algorithms'), ('SYSTEM_DESIGN', 'System Design'), ('RAPID_FIRE', 'Rapid Fire QnA')], max_length=30, verbose_name='interview type'),
        ),
    ]
