# Generated by Django 6.0.2 on 2026-06-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_alter_interviewsession_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='difficulty',
            field=models.CharField(blank=True, help_text='Experience level mapping (e.g., Easy, Expert)', max_length=50, null=True, verbose_name='difficulty'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='language',
            field=models.CharField(blank=True, help_text='Programming language (e.g., Python, Java)', max_length=50, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='type',
            field=models.CharField(choices=[('DSA', 'Data Structures & Algorithms'), ('SYSTEM_DESIGN', 'System Design'), ('RAPID_FIRE', 'Rapid Fire QnA'), ('SKILL_BASED', 'Skill Based')], max_length=30, verbose_name='interview type'),
        ),
    ]
