# Generated by Django 6.0.2 on 2026-06-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_interviewsession_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='violations',
            field=models.PositiveIntegerField(default=0, help_text='Number of anti-cheat violations detected.', verbose_name='violations'),
        ),
    ]
