# Generated by Django 6.0.2 on 2026-06-19 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_interviewsession_violations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aievaluation',
            name='score',
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='final_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Overall score assigned by the AI evaluator (0-100).', verbose_name='final score'),
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='scores',
            field=models.JSONField(default=dict, help_text='Nested dictionary of scores for problem understanding, approach, code quality, etc.', verbose_name='scores'),
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='verdict',
            field=models.CharField(blank=True, help_text="Final decision (e.g. 'hire', 'no_hire').", max_length=50, verbose_name='verdict'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='evaluated at'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='started at'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='submitted at'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='time_taken_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='time taken seconds'),
        ),
        migrations.CreateModel(
            name='UserPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_score', models.FloatField(default=0.0, verbose_name='average score')),
                ('last_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='last score')),
                ('total_attempts', models.PositiveIntegerField(default=0, verbose_name='total attempts')),
                ('weak_areas', models.JSONField(default=list, verbose_name='weak areas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user performance',
                'verbose_name_plural': 'user performances',
                'db_table': 'interviews_user_performance',
            },
        ),
        migrations.CreateModel(
            name='SkillBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='category')),
                ('score', models.PositiveSmallIntegerField(verbose_name='score')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_breakdowns', to='interviews.interviewsession')),
            ],
            options={
                'verbose_name': 'skill breakdown',
                'verbose_name_plural': 'skill breakdowns',
                'db_table': 'interviews_skill_breakdown',
                'ordering': ['category'],
                'unique_together': {('interview', 'category')},
            },
        ),
    ]
